/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32_F103x6.h"
#include "Stm32_F103C6_gpio_driver.h"
#include "Stm32_F103C6_EXTI_driver.h"
#include "Stm32_F103C6_USART_driver.h"
#include "lcd_driver.h"
#include "keypad_driver.h"
#include "Stm32_F103C6_SPI_driver.h"
#include "Stm32_F103C6_I2C_driver.h"
#include "I2C_Slave_EEPROM.h"
#include "TIM.h"

uint32_t IRQ_flag = 0;

void clock_init()
{
	//Enable port A clock
	RCC_GPIOA_CLK_EN();
	//Enable port B clock
	RCC_GPIOB_CLK_EN();
	//Enable AFIO clock
	RCC_AFIO_CLK_EN();
}

void IRQ_EXTI9_callback(void){
	IRQ_flag = 1;
}

int VAL1=0;
int main(void)
{
	clock_init();
	EXTI_PinConfig_t EXTI_cfg;
	EXTI_cfg.EXTI_PIN = EXTI9PB9;
	EXTI_cfg.Trigger_Case = EXTI_Trigger_RISING;
	EXTI_cfg.P_IRQ_CALLBACK = IRQ_EXTI9_callback;
	EXTI_cfg.IRQ_EN = EXTI_IRQ_Enable;
	MCAL_EXTI_GPIO_Init(&EXTI_cfg);
	IRQ_flag = 1;

	__asm("nop \n\t nop \n\t nop");

	//mov VAL1,oxff
	__asm("mov %0 ,#0xff"
			:"=r" (VAL1) );
	__asm("nop \n\t nop \n\t nop");

	while(1){
		if(IRQ_flag){
			IRQ_flag = 0;
		}
	}
}
